# You can override the included template(s) by including variable overrides
# SAST customization: https://docs.gitlab.com/ee/user/application_security/sast/#customizing-the-sast-settings
# Secret Detection customization: https://docs.gitlab.com/ee/user/application_security/secret_detection/#customizing-settings
# Dependency Scanning customization: https://docs.gitlab.com/ee/user/application_security/dependency_scanning/#customizing-the-dependency-scanning-settings
# Container Scanning customization: https://docs.gitlab.com/ee/user/application_security/container_scanning/#customizing-the-container-scanning-settings
# Note that environment variables can be set in several places
# See https://docs.gitlab.com/ee/ci/variables/#cicd-variable-precedence

stages:
- gitlab-test
- lint
- sonarqube-check
- test
- scout
- publish

variables:
  ANSIBLE_FORCE_COLOR: "true"
  PY_COLORS: "1"
  #
  DOCKER_IMAGE_ALPINE_SONAR_SCANNER_CLI: "robincbz/alpine-sonarcli:latest"
  DOCKER_IMAGE_ALPINE_GIT: robincbz/alpine-git:latest
  DOCKER_IMAGE_ALPINE_RELEASE_CLI: "robincbz/alpine-releasecli:latest"
  DOCKER_IMAGE_ALPINE_DOCKERFILE_LINT: "robincbz/alpine-dockerfilelint:latest"
  DOCKER_IMAGE_MARKDOWN_LINT: "robincbz/debian-markdownlint:latest"
  DOCKER_IMAGE_DOCKER_DOCKERFILE_BUILD: "robincbz/docker-dockerfilebuild:latest"
  DOCKER_IMAGE_DOCKER_SECRET_LINT: "robincbz/alpine-secretlint:latest"
  DOCKER_IMAGE_DOCKER_SCOUT: "robincbz/docker-scout:latest"

###############################################################################
#################### EXTENDABLES
###############################################################################

.test: &test
  stage: test
  image: $NEXUS_REPOS_DOCKER_REGISTRY/$DOCKER_IMAGE_DOCKER_DOCKERFILE_BUILD
  script:
    - "cd $(pwd)/${TYPE}/${NAME}/latest && bash build --test"
  allow_failure: false
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
    - if: '$CI_COMMIT_BRANCH == "develop"'

.scout: &scout
  stage: scout
  image: $NEXUS_REPOS_DOCKER_REGISTRY/$DOCKER_IMAGE_DOCKER_SCOUT
  before_script:
    - "docker login -u \"${DOCKER_HUB_REPOS_USERNAME}\" -p \"${DOCKER_HUB_REPOS_PASSWORD}\""
    - "cd $(pwd)/${TYPE}/${NAME}/latest"
    - "bash build --scout"
    - "cd ../../../ && pwd"
  script:
    - "docker scout cves --exit-code --only-severity critical,high --format markdown --output ./cves-report.md local://local/${NAME}:latest-scout || true"
    - "docker scout recommendations local://local/${NAME}:latest-scout || true"
  allow_failure: true
  artifacts:
    expire_in: "1 month"
    paths:
      - "cves-report.md"
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
    - if: '$CI_COMMIT_BRANCH == "develop"'

.publish: &publish
  stage: publish
  image: $NEXUS_REPOS_DOCKER_REGISTRY/$DOCKER_IMAGE_DOCKER_DOCKERFILE_BUILD
  before_script:
    - "docker login -u \"${DOCKER_HUB_REPOS_USERNAME}\" -p \"${DOCKER_HUB_REPOS_PASSWORD}\""
  script:
    - "cd $(pwd)/${TYPE}/${NAME}/latest && bash build --cicd"
  allow_failure: false
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'

###############################################################################
#################### CI JOBS
###############################################################################

############################################
#### gitlab-test
############################################

# As a GitLab ci, we use the default template :)
sast:
  stage: gitlab-test
include:
- template: Security/SAST.gitlab-ci.yml
  allow_failure: false

############################################
#### lint
############################################

dockerfile-lint:
  stage: lint
  image: $NEXUS_REPOS_DOCKER_REGISTRY/$DOCKER_IMAGE_ALPINE_DOCKERFILE_LINT
  script:
    - "hadolint --ignore DL3018 --ignore DL3013 --ignore DL3008 --ignore DL3009 --ignore DL3015 $(pwd)/*/*/latest/Dockerfile"
  allow_failure: false

markdown-lint:
  stage: lint
  image: $NEXUS_REPOS_DOCKER_REGISTRY/$DOCKER_IMAGE_MARKDOWN_LINT
  script:
    - markdownlint './README.md' --disable MD013
    - markdownlint './*/*/latest/README.md' --disable MD013
  allow_failure: false

secret-lint:
  stage: lint
  image: $NEXUS_REPOS_DOCKER_REGISTRY/$DOCKER_IMAGE_DOCKER_SECRET_LINT
  script:
    - "detect-secrets scan"
    - "detect-secrets audit .secrets.baseline"
  allow_failure: false

############################################
#### sonarqube
############################################

sonarqube-check:
  stage: sonarqube-check
  image: 
    name: $NEXUS_REPOS_DOCKER_REGISTRY/$DOCKER_IMAGE_ALPINE_SONAR_SCANNER_CLI
    entrypoint: [""]
  variables:
    SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"  # Defines the location of the analysis task cache
    GIT_DEPTH: "0"  # Tells git to fetch all the branches of the project, required by the analysis task
  cache:
    key: "${CI_JOB_NAME}"
    paths:
      - ".sonar/cache"
  script: 
    - "sonar-scanner -X"

############################################
#### test
############################################

test_debian_11_ansible:
  <<: *test
  variables:
    TYPE: "Ansible"
    NAME: "debian-11-ansible"

test_debian_12_ansible:
  <<: *test
  variables:
    TYPE: "Ansible"
    NAME: "debian-12-ansible"

test_docker_dind_ansible:
  <<: *test
  variables:
    TYPE: "Ansible"
    NAME: "docker-dind-ansible"

test_docker_dind_molecule:
  <<: *test
  variables:
    TYPE: "Ansible"
    NAME: "docker-dind-molecule"

test_ubuntu_22_ansible:
  <<: *test
  variables:
    TYPE: "Ansible"
    NAME: "ubuntu-22-ansible"

test_debian_11_certification:
  <<: *test
  variables:
    TYPE: "Build"
    NAME: "debian-11-certification"

test_debian_npmbuild:
  <<: *test
  variables:
    TYPE: "Build"
    NAME: "debian-npmbuild"

test_docker_dockerfilebuild:
  <<: *test
  variables:
    TYPE: "Build"
    NAME: "docker-dockerfilebuild"

test_alpine_ansiblelint:
  <<: *test
  variables:
    TYPE: "Lint"
    NAME: "alpine-ansiblelint"

test_alpine_dockerfilelint:
  <<: *test
  variables:
    TYPE: "Lint"
    NAME: "alpine-dockerfilelint"

test_alpine_jinjalint:
  <<: *test
  variables:
    TYPE: "Lint"
    NAME: "alpine-jinjalint"

test_alpine_secretlint:
  <<: *test
  variables:
    TYPE: "Lint"
    NAME: "alpine-secretlint"

test_alpine_sonarcli:
  <<: *test
  variables:
    TYPE: "Lint"
    NAME: "alpine-sonarcli"

test_alpine_yamllint:
  <<: *test
  variables:
    TYPE: "Lint"
    NAME: "alpine-yamllint"

test_alpine_markdownlint:
  <<: *test
  variables:
    TYPE: "Lint"
    NAME: "debian-markdownlint"

test_alpine_git:
  <<: *test
  variables:
    TYPE: "Publish"
    NAME: "alpine-git"

test_alpine_releasecli:
  <<: *test
  variables:
    TYPE: "Publish"
    NAME: "alpine-releasecli"

test_alpine_nginx:
  <<: *test
  variables:
    TYPE: "Hosting"
    NAME: "alpine-nginx"

############################################
#### scout
############################################

scout_debian_11_ansible:
  <<: *scout
  variables:
    TYPE: "Ansible"
    NAME: "debian-11-ansible"
  needs:
    - "test_debian_11_ansible"

scout_debian_12_ansible:
  <<: *scout
  variables:
    TYPE: "Ansible"
    NAME: "debian-12-ansible"
  needs:
    - "test_debian_12_ansible"

scout_docker_dind_ansible:
  <<: *scout
  variables:
    TYPE: "Ansible"
    NAME: "docker-dind-ansible"
  needs:
    - "test_docker_dind_ansible"

scout_docker_dind_molecule:
  <<: *scout
  variables:
    TYPE: "Ansible"
    NAME: "docker-dind-molecule"
  needs:
    - "test_docker_dind_molecule"

scout_ubuntu_22_ansible:
  <<: *scout
  variables:
    TYPE: "Ansible"
    NAME: "ubuntu-22-ansible"
  needs:
    - "test_ubuntu_22_ansible"

scout_debian_11_certification:
  <<: *scout
  variables:
    TYPE: "Build"
    NAME: "debian-11-certification"
  needs:
    - "test_debian_11_certification"

scout_debian_npmbuild:
  <<: *scout
  variables:
    TYPE: "Build"
    NAME: "debian-npmbuild"
  needs:
    - "test_debian_npmbuild"

scout_docker_dockerfilebuild:
  <<: *scout
  variables:
    TYPE: "Build"
    NAME: "docker-dockerfilebuild"
  needs:
    - "test_docker_dockerfilebuild"

scout_alpine_ansiblelint:
  <<: *scout
  variables:
    TYPE: "Lint"
    NAME: "alpine-ansiblelint"
  needs:
    - "test_alpine_ansiblelint"

scout_alpine_dockerfilelint:
  <<: *scout
  variables:
    TYPE: "Lint"
    NAME: "alpine-dockerfilelint"
  needs:
    - "test_alpine_dockerfilelint"

scout_alpine_jinjalint:
  <<: *scout
  variables:
    TYPE: "Lint"
    NAME: "alpine-jinjalint"
  needs:
    - "test_alpine_jinjalint"

scout_alpine_secretlint:
  <<: *scout
  variables:
    TYPE: "Lint"
    NAME: "alpine-secretlint"
  needs:
    - "test_alpine_secretlint"

scout_alpine_sonarcli:
  <<: *scout
  variables:
    TYPE: "Lint"
    NAME: "alpine-sonarcli"
  needs:
    - "test_alpine_sonarcli"

scout_alpine_yamllint:
  <<: *scout
  variables:
    TYPE: "Lint"
    NAME: "alpine-yamllint"
  needs:
    - "test_alpine_yamllint"

scout_alpine_markdownlint:
  <<: *scout
  variables:
    TYPE: "Lint"
    NAME: "debian-markdownlint"
  needs:
    - "test_alpine_markdownlint"

scout_alpine_git:
  <<: *scout
  variables:
    TYPE: "Publish"
    NAME: "alpine-git"
  needs:
    - "test_alpine_git"

scout_alpine_releasecli:
  <<: *scout
  variables:
    TYPE: "Publish"
    NAME: "alpine-releasecli"
  needs:
    - "test_alpine_releasecli"

scout_alpine_nginx:
  <<: *scout
  variables:
    TYPE: "Hosting"
    NAME: "alpine-nginx"
  needs:
    - "test_alpine_nginx"

############################################
#### publish
############################################

publish_debian_11_ansible:
  <<: *publish
  variables:
    TYPE: "Ansible"
    NAME: "debian-11-ansible"
  needs:
    - "scout_debian_11_ansible"

publish_debian_12_ansible:
  <<: *publish
  variables:
    TYPE: "Ansible"
    NAME: "debian-12-ansible"
  needs:
    - "scout_debian_12_ansible"

publish_docker_dind_ansible:
  <<: *publish
  variables:
    TYPE: "Ansible"
    NAME: "docker-dind-ansible"
  needs:
    - "scout_docker_dind_ansible"

publish_docker_dind_molecule:
  <<: *publish
  variables:
    TYPE: "Ansible"
    NAME: "docker-dind-molecule"
  needs:
    - "scout_docker_dind_molecule"

publish_ubuntu_22_ansible:
  <<: *publish
  variables:
    TYPE: "Ansible"
    NAME: "ubuntu-22-ansible"
  needs:
    - "scout_ubuntu_22_ansible"

publish_debian_11_certification:
  <<: *publish
  variables:
    TYPE: "Build"
    NAME: "debian-11-certification"
  needs:
    - "scout_debian_11_certification"

publish_debian_npmbuild:
  <<: *publish
  variables:
    TYPE: "Build"
    NAME: "debian-npmbuild"
  needs:
    - "scout_debian_npmbuild"

publish_docker_dockerfilebuild:
  <<: *publish
  variables:
    TYPE: "Build"
    NAME: "docker-dockerfilebuild"
  needs:
    - "scout_docker_dockerfilebuild"

publish_alpine_ansiblelint:
  <<: *publish
  variables:
    TYPE: "Lint"
    NAME: "alpine-ansiblelint"
  needs:
    - "scout_alpine_ansiblelint"

publish_alpine_dockerfilelint:
  <<: *publish
  variables:
    TYPE: "Lint"
    NAME: "alpine-dockerfilelint"
  needs:
    - "scout_alpine_dockerfilelint"

publish_alpine_jinjalint:
  <<: *publish
  variables:
    TYPE: "Lint"
    NAME: "alpine-jinjalint"
  needs:
    - "scout_alpine_jinjalint"

publish_alpine_secretlint:
  <<: *publish
  variables:
    TYPE: "Lint"
    NAME: "alpine-secretlint"
  needs:
    - "scout_alpine_secretlint"

publish_alpine_sonarcli:
  <<: *publish
  variables:
    TYPE: "Lint"
    NAME: "alpine-sonarcli"
  needs:
    - "scout_alpine_sonarcli"

publish_alpine_yamllint:
  <<: *publish
  variables:
    TYPE: "Lint"
    NAME: "alpine-yamllint"
  needs:
    - "scout_alpine_yamllint"

publish_alpine_markdownlint:
  <<: *publish
  variables:
    TYPE: "Lint"
    NAME: "debian-markdownlint"
  needs:
    - "scout_alpine_markdownlint"

publish_alpine_git:
  <<: *publish
  variables:
    TYPE: "Publish"
    NAME: "alpine-git"
  needs:
    - "scout_alpine_git"

publish_alpine_releasecli:
  <<: *publish
  variables:
    TYPE: "Publish"
    NAME: "alpine-releasecli"
  needs:
    - "scout_alpine_releasecli"

publish_alpine_nginx:
  <<: *publish
  variables:
    TYPE: "Hosting"
    NAME: "alpine-nginx"
  needs:
    - "scout_alpine_nginx"
