# You can override the included template(s) by including variable overrides
# SAST customization: https://docs.gitlab.com/ee/user/application_security/sast/#customizing-the-sast-settings
# Secret Detection customization: https://docs.gitlab.com/ee/user/application_security/secret_detection/#customizing-settings
# Dependency Scanning customization: https://docs.gitlab.com/ee/user/application_security/dependency_scanning/#customizing-the-dependency-scanning-settings
# Container Scanning customization: https://docs.gitlab.com/ee/user/application_security/container_scanning/#customizing-the-container-scanning-settings
# Note that environment variables can be set in several places
# See https://docs.gitlab.com/ee/ci/variables/#cicd-variable-precedence

stages:
- gitlab-test
- hadolint
- testbuild
- cicdbuild

###############################################################################
#################### actions
###############################################################################

# To start, we need to lint Dockerfile with hadolint
.hadolint: &hadolint
  stage: hadolint
  image: $NEXUS_ADDRESS/$DOCKER_IMAGE_DOCKERFILE_LINT
  script:
    - "hadolint --ignore DL3018 --ignore DL3013 --ignore DL3008 --ignore DL3009 --ignore DL3015 $(pwd)/$TYPE/$NAME/latest/Dockerfile"
  allow_failure: false
  retry: 2
  rules:
    - if: $CI_COMMIT_BRANCH == "develop"

# After that we will try to build the Dockerfile
.testbuild: &testbuild
  stage: testbuild
  image: $NEXUS_ADDRESS/$DOCKER_IMAGE_DOCKERFILE_BUILD
  script:
    - "cd $(pwd)/$TYPE/$NAME/latest"
    - "bash build --testbuild"
  allow_failure: false
  retry: 2
  rules:
    - if: $CI_COMMIT_BRANCH == "develop"

# After that we will build the Dockerfile and push it as cicd
.cicdbuild: &cicdbuild
  stage: cicdbuild
  image: $NEXUS_ADDRESS/$DOCKER_IMAGE_DOCKERFILE_BUILD
  script:
    - "docker login -u \"$DOCKER_HUB_REPOS_USERNAME\" -p \"$DOCKER_HUB_REPOS_PASSWORD\""
    - "cd $(pwd)/$TYPE/$NAME/latest"
    - "bash build --cicdbuild"
  allow_failure: false
  retry: 2
  rules:
    - if: $CI_COMMIT_BRANCH == "main"

###############################################################################
#################### CI JOBS
###############################################################################

############################################
#### gitlab-test
############################################

# As a GitLab ci, we use the default template :)
sast:
  stage: gitlab-test
include:
- template: Security/SAST.gitlab-ci.yml
  allow_failure: false

############################################
#### hadolint
############################################

hadolint_alpine_ansiblelint:
  <<: *hadolint
  variables:
    TYPE: "Lint"
    NAME: "alpine-ansiblelint"

hadolint_alpine_dockerfilelint:
  <<: *hadolint
  variables:
    TYPE: "Lint"
    NAME: "alpine-dockerfilelint"

hadolint_alpine_jinjalint:
  <<: *hadolint
  variables:
    TYPE: "Lint"
    NAME: "alpine-jinjalint"

hadolint_alpine_yamllint:
  <<: *hadolint
  variables:
    TYPE: "Lint"
    NAME: "alpine-yamllint"

hadolint_debian_11_ansible:
  <<: *hadolint
  variables:
    TYPE: "Ansible"
    NAME: "debian-11-ansible"

hadolint_ubuntu_22_ansible:
  <<: *hadolint
  variables:
    TYPE: "Ansible"
    NAME: "ubuntu-22-ansible"

hadolint_docker_dind_molecule:
  <<: *hadolint
  variables:
    TYPE: "Ansible"
    NAME: "docker-dind-molecule"

hadolint_docker_dind_ansible:
  <<: *hadolint
  variables:
    TYPE: "Ansible"
    NAME: "docker-dind-ansible"

hadolint_docker_dockerfilebuild:
  <<: *hadolint
  variables:
    TYPE: "Build"
    NAME: "docker-dockerfilebuild"

hadolint_debian_11_certification:
  <<: *hadolint
  variables:
    TYPE: "Build"
    NAME: "debian-11-certification"

hadolint_alpine_git:
  <<: *hadolint
  variables:
    TYPE: "Publish"
    NAME: "alpine-git"

############################################
#### testbuild
############################################

testbuild_alpine_ansiblelint:
  <<: *testbuild
  variables:
    TYPE: "Lint"
    NAME: "alpine-ansiblelint"
  needs:
    - "hadolint_alpine_ansiblelint"

testbuild_alpine_dockerfilelint:
  <<: *testbuild
  variables:
    TYPE: "Lint"
    NAME: "alpine-dockerfilelint"
  needs:
    - "hadolint_alpine_dockerfilelint"

testbuild_alpine_jinjalint:
  <<: *testbuild
  variables:
    TYPE: "Lint"
    NAME: "alpine-jinjalint"
  needs:
    - "hadolint_alpine_jinjalint"

testbuild_alpine_yamllint:
  <<: *testbuild
  variables:
    TYPE: "Lint"
    NAME: "alpine-yamllint"
  needs:
    - "hadolint_alpine_yamllint"

testbuild_debian_11_ansible:
  <<: *testbuild
  variables:
    TYPE: "Ansible"
    NAME: "debian-11-ansible"
  needs:
    - "hadolint_debian_11_ansible"

testbuild_ubuntu_22_ansible:
  <<: *testbuild
  variables:
    TYPE: "Ansible"
    NAME: "ubuntu-22-ansible"
  needs:
    - "hadolint_ubuntu_22_ansible"

testbuild_docker_dind_molecule:
  <<: *testbuild
  variables:
    TYPE: "Ansible"
    NAME: "docker-dind-molecule"
  needs:
    - "hadolint_docker_dind_molecule"

testbuild_docker_dind_ansible:
  <<: *testbuild
  variables:
    TYPE: "Ansible"
    NAME: "docker-dind-ansible"
  needs:
    - "hadolint_docker_dind_ansible"

testbuild_docker_dockerfilebuild:
  <<: *testbuild
  variables:
    TYPE: "Build"
    NAME: "docker-dockerfilebuild"
  needs:
    - "hadolint_docker_dockerfilebuild"

testbuild_debian_11_certification:
  <<: *testbuild
  variables:
    TYPE: "Build"
    NAME: "debian-11-certification"
  needs:
    - "hadolint_debian_11_certification"

testbuild_alpine_git:
  <<: *testbuild
  variables:
    TYPE: "Publish"
    NAME: "alpine-git"
  needs:
    - "hadolint_alpine_git"

############################################
#### cicdbuild
############################################

cicdbuild_alpine_ansiblelint:
  <<: *cicdbuild
  variables:
    TYPE: "Lint"
    NAME: "alpine-ansiblelint"

cicdbuild_alpine_dockerfilelint:
  <<: *cicdbuild
  variables:
    TYPE: "Lint"
    NAME: "alpine-dockerfilelint"

cicdbuild_alpine_jinjalint:
  <<: *cicdbuild
  variables:
    TYPE: "Lint"
    NAME: "alpine-jinjalint"

cicdbuild_alpine_yamllint:
  <<: *cicdbuild
  variables:
    TYPE: "Lint"
    NAME: "alpine-yamllint"

cicdbuild_debian_11_ansible:
  <<: *cicdbuild
  variables:
    TYPE: "Ansible"
    NAME: "debian-11-ansible"

cicdbuild_debian_12_ansible:
  <<: *cicdbuild
  variables:
    TYPE: "Ansible"
    NAME: "debian-12-ansible"

cicdbuild_ubuntu_22_ansible:
  <<: *cicdbuild
  variables:
    TYPE: "Ansible"
    NAME: "ubuntu-22-ansible"

cicdbuild_docker_dind_molecule:
  <<: *cicdbuild
  variables:
    TYPE: "Ansible"
    NAME: "docker-dind-molecule"

cicdbuild_docker_dind_ansible:
  <<: *cicdbuild
  variables:
    TYPE: "Ansible"
    NAME: "docker-dind-ansible"

cicdbuild_docker_dockerfilebuild:
  <<: *cicdbuild
  variables:
    TYPE: "Build"
    NAME: "docker-dockerfilebuild"

cicdbuild_debian_11_certification:
  <<: *cicdbuild
  variables:
    TYPE: "Build"
    NAME: "debian-11-certification"

cicdbuild_alpine_git:
  <<: *cicdbuild
  variables:
    TYPE: "Publish"
    NAME: "alpine-git"