# You can override the included template(s) by including variable overrides
# SAST customization: https://docs.gitlab.com/ee/user/application_security/sast/#customizing-the-sast-settings
# Secret Detection customization: https://docs.gitlab.com/ee/user/application_security/secret_detection/#customizing-settings
# Dependency Scanning customization: https://docs.gitlab.com/ee/user/application_security/dependency_scanning/#customizing-the-dependency-scanning-settings
# Container Scanning customization: https://docs.gitlab.com/ee/user/application_security/container_scanning/#customizing-the-container-scanning-settings
# Note that environment variables can be set in several places
# See https://docs.gitlab.com/ee/ci/variables/#cicd-variable-precedence

stages:
- gitlab-test
- hadolint

###############################################################################
#################### actions
###############################################################################

# To start, we need to lint Dockerfile with hadolint
.hadolint: &hadolint
  stage: hadolint
  image: $DOCKER_IMAGE_DOCKERFILE_LINT
  script:
    - "hadolint --trusted-registry $NEXUS_ADDRESS --ignore DL3108 $(pwd)/$path/Dockerfile"
  allow_failure: false
  retry: 2

###############################################################################
#################### CI JOBS
###############################################################################

############################################
#### gitlab-test
############################################

# As a GitLab ci, we use the default template :)
sast:
  stage: gitlab-test
include:
- template: Security/SAST.gitlab-ci.yml
  allow_failure: false

############################################
#### hadolint
############################################

hadolint_alpine_ansiblelint:
  <<: *hadolint
  variables:
    path: "Alpine/alpine-ansiblelint/3.18"

hadolint_alpine_dockerfilelint:
  <<: *hadolint
  variables:
    path: "Alpine/alpine-dockerfilelint/3.18"

hadolint_alpine_jinjalint:
  <<: *hadolint
  variables:
    path: "Alpine/alpine-jinjalint/3.18"

hadolint_alpine_yamllint:
  <<: *hadolint
  variables:
    path: "Alpine/alpine-yamllint/3.18"

hadolint_debian_ansible:
  <<: *hadolint
  variables:
    path: "Debian/debian-ansible/11"

hadolint_docker_molecule:
  <<: *hadolint
  variables:
    path: "Docker/docker-molecule/dind"