# You can override the included template(s) by including variable overrides
# SAST customization: https://docs.gitlab.com/ee/user/application_security/sast/#customizing-the-sast-settings
# Secret Detection customization: https://docs.gitlab.com/ee/user/application_security/secret_detection/#customizing-settings
# Dependency Scanning customization: https://docs.gitlab.com/ee/user/application_security/dependency_scanning/#customizing-the-dependency-scanning-settings
# Container Scanning customization: https://docs.gitlab.com/ee/user/application_security/container_scanning/#customizing-the-container-scanning-settings
# Note that environment variables can be set in several places
# See https://docs.gitlab.com/ee/ci/variables/#cicd-variable-precedence

stages:
- gitlab-test
- lint
- secret
- sonarqube
- testbuild
- security
- publish

variables:
  ANSIBLE_FORCE_COLOR: "true"
  PY_COLORS: "1"
  #
  DOCKER_IMAGE_ALPINE_SONAR_SCANNER_CLI: "robincbz/alpine-sonarcli:latest"
  DOCKER_IMAGE_ALPINE_GIT: robincbz/alpine-git:latest
  DOCKER_IMAGE_ALPINE_RELEASE_CLI: "robincbz/alpine-releasecli:latest"
  DOCKER_IMAGE_ALPINE_DOCKERFILE_LINT: "robincbz/alpine-dockerfilelint:latest"
  DOCKER_IMAGE_DOCKER_DOCKERFILE_BUILD: "robincbz/docker-dockerfilebuild:latest"
  DOCKER_IMAGE_DOCKER_SECRET_LINT: "robincbz/alpine-secretlint:latest"
  DOCKER_IMAGE_DOCKER_SCOUT: "robincbz/docker-scout:latest"

###############################################################################
#################### EXTENDABLES
###############################################################################

.testbuild: &testbuild
  stage: testbuild
  image: $NEXUS_REPOS_DOCKER_REGISTRY/$DOCKER_IMAGE_DOCKER_DOCKERFILE_BUILD
  script:
    - "cd $(pwd)/${TYPE}/${NAME}/latest && bash build --testbuild"
  allow_failure: false
  rules:
    - if: '$CI_COMMIT_BRANCH == "develop"'
    - if: '$CI_COMMIT_BRANCH == "main"'

.security: &security
  stage: security
  image: $NEXUS_REPOS_DOCKER_REGISTRY/$DOCKER_IMAGE_DOCKER_SCOUT
  before_script:
    - "docker login -u \"${DOCKER_HUB_REPOS_USERNAME}\" -p \"${DOCKER_HUB_REPOS_PASSWORD}\""
    - "cd $(pwd)/${TYPE}/${NAME}/latest"
    - "bash build --dockerscout"
    - "cd ../../ && pwd"
  script:
    - "docker scout cves --format markdown --output ./cves-report.md local://local/${NAME}:docker-scout"
    - "docker scout recommendations local://local/${NAME}:docker-scout"
  allow_failure: false
  rules:
    - if: '$CI_COMMIT_BRANCH == "develop"'
    - if: '$CI_COMMIT_BRANCH == "main"'
  artifacts:
    expire_in: "1 month"
    paths:
      - "cves-report.md"

.publish: &publish
  stage: publish
  image: $NEXUS_REPOS_DOCKER_REGISTRY/$DOCKER_IMAGE_DOCKER_SCOUT
  before_script:
    - "docker login -u \"${DOCKER_HUB_REPOS_USERNAME}\" -p \"${DOCKER_HUB_REPOS_PASSWORD}\""
  script:
    - "cd $(pwd)/${TYPE}/${NAME}/latest && bash build --cicdbuild"
  allow_failure: false
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'

###############################################################################
#################### CI JOBS
###############################################################################

############################################
#### gitlab-test
############################################

# As a GitLab ci, we use the default template :)
sast:
  stage: gitlab-test
include:
- template: Security/SAST.gitlab-ci.yml
  allow_failure: false

############################################
#### lint
############################################

hadolint:
  stage: lint
  image: $NEXUS_REPOS_DOCKER_REGISTRY/$DOCKER_IMAGE_ALPINE_DOCKERFILE_LINT
  script:
    - "hadolint --ignore DL3018 --ignore DL3013 --ignore DL3008 --ignore DL3009 --ignore DL3015 $(pwd)/*/*/latest/Dockerfile"
  allow_failure: false

############################################
#### secret
############################################

secretlint:
  stage: secret
  image: $NEXUS_REPOS_DOCKER_REGISTRY/$DOCKER_IMAGE_DOCKER_SECRET_LINT
  script:
    #- "detect-secrets -C $(pwd) scan > .secrets.baseline"
    - "detect-secrets scan"
    - "detect-secrets audit .secrets.baseline"
  allow_failure: false

############################################
#### sonarqube
############################################

sonarqube-check:
  stage: sonarqube
  image: 
    name: $NEXUS_REPOS_DOCKER_REGISTRY/$DOCKER_IMAGE_ALPINE_SONAR_SCANNER_CLI
    entrypoint: [""]
  variables:
    SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"  # Defines the location of the analysis task cache
    GIT_DEPTH: "0"  # Tells git to fetch all the branches of the project, required by the analysis task
  cache:
    key: "${CI_JOB_NAME}"
    paths:
      - ".sonar/cache"
  script: 
    - "sonar-scanner"

############################################
#### testbuild
############################################

testbuild_debian_11_ansible:
  <<: *testbuild
  variables:
    TYPE: "Ansible"
    NAME: "debian-11-ansible"

testbuild_debian_12_ansible:
  <<: *testbuild
  variables:
    TYPE: "Ansible"
    NAME: "debian-12-ansible"

testbuild_docker_dind_ansible:
  <<: *testbuild
  variables:
    TYPE: "Ansible"
    NAME: "docker-dind-ansible"

testbuild_docker_dind_molecule:
  <<: *testbuild
  variables:
    TYPE: "Ansible"
    NAME: "docker-dind-molecule"

testbuild_ubuntu_22_ansible:
  <<: *testbuild
  variables:
    TYPE: "Ansible"
    NAME: "ubuntu-22-ansible"

testbuild_debian_11_certification:
  <<: *testbuild
  variables:
    TYPE: "Build"
    NAME: "debian-11-certification"

testbuild_debian_npmbuild:
  <<: *testbuild
  variables:
    TYPE: "Build"
    NAME: "debian-npmbuild"

testbuild_docker_dockerfilebuild:
  <<: *testbuild
  variables:
    TYPE: "Build"
    NAME: "docker-dockerfilebuild"

testbuild_alpine_ansiblelint:
  <<: *testbuild
  variables:
    TYPE: "Lint"
    NAME: "alpine-ansiblelint"

testbuild_alpine_dockerfilelint:
  <<: *testbuild
  variables:
    TYPE: "Lint"
    NAME: "alpine-dockerfilelint"

testbuild_alpine_jinjalint:
  <<: *testbuild
  variables:
    TYPE: "Lint"
    NAME: "alpine-jinjalint"

testbuild_alpine_secretlint:
  <<: *testbuild
  variables:
    TYPE: "Lint"
    NAME: "alpine-secretlint"

testbuild_alpine_sonarcli:
  <<: *testbuild
  variables:
    TYPE: "Lint"
    NAME: "alpine-sonarcli"

testbuild_alpine_yamllint:
  <<: *testbuild
  variables:
    TYPE: "Lint"
    NAME: "alpine-yamllint"

testbuild_alpine_markdownlint:
  <<: *testbuild
  variables:
    TYPE: "Lint"
    NAME: "debian-markdownlint"

testbuild_alpine_git:
  <<: *testbuild
  variables:
    TYPE: "Publish"
    NAME: "alpine-git"

testbuild_alpine_releasecli:
  <<: *testbuild
  variables:
    TYPE: "Publish"
    NAME: "alpine-releasecli"

############################################
#### security
############################################

security_debian_11_ansible:
  <<: *security
  variables:
    TYPE: "Ansible"
    NAME: "debian-11-ansible"
  needs:
    - "testbuild_debian_11_ansible"

security_debian_12_ansible:
  <<: *security
  variables:
    TYPE: "Ansible"
    NAME: "debian-12-ansible"
  needs:
    - "testbuild_debian_12_ansible"

security_docker_dind_ansible:
  <<: *security
  variables:
    TYPE: "Ansible"
    NAME: "docker-dind-ansible"
  needs:
    - "testbuild_docker_dind_ansible"

security_docker_dind_molecule:
  <<: *security
  variables:
    TYPE: "Ansible"
    NAME: "docker-dind-molecule"
  needs:
    - "testbuild_docker_dind_molecule"

security_ubuntu_22_ansible:
  <<: *security
  variables:
    TYPE: "Ansible"
    NAME: "ubuntu-22-ansible"
  needs:
    - "testbuild_ubuntu_22_ansible"

security_debian_11_certification:
  <<: *security
  variables:
    TYPE: "Build"
    NAME: "debian-11-certification"
  needs:
    - "testbuild_debian_11_certification"

security_debian_npmbuild:
  <<: *security
  variables:
    TYPE: "Build"
    NAME: "debian-npmbuild"
  needs:
    - "testbuild_debian_npmbuild"

security_docker_dockerfilebuild:
  <<: *security
  variables:
    TYPE: "Build"
    NAME: "docker-dockerfilebuild"
  needs:
    - "testbuild_docker_dockerfilebuild"

security_alpine_ansiblelint:
  <<: *security
  variables:
    TYPE: "Lint"
    NAME: "alpine-ansiblelint"
  needs:
    - "testbuild_alpine_ansiblelint"

security_alpine_dockerfilelint:
  <<: *security
  variables:
    TYPE: "Lint"
    NAME: "alpine-dockerfilelint"
  needs:
    - "testbuild_alpine_dockerfilelint"

security_alpine_jinjalint:
  <<: *security
  variables:
    TYPE: "Lint"
    NAME: "alpine-jinjalint"
  needs:
    - "testbuild_alpine_jinjalint"

security_alpine_secretlint:
  <<: *security
  variables:
    TYPE: "Lint"
    NAME: "alpine-secretlint"
  needs:
    - "testbuild_alpine_secretlint"

security_alpine_sonarcli:
  <<: *security
  variables:
    TYPE: "Lint"
    NAME: "alpine-sonarcli"
  needs:
    - "testbuild_alpine_sonarcli"

security_alpine_yamllint:
  <<: *security
  variables:
    TYPE: "Lint"
    NAME: "alpine-yamllint"
  needs:
    - "testbuild_alpine_yamllint"

security_alpine_markdownlint:
  <<: *security
  variables:
    TYPE: "Lint"
    NAME: "debian-markdownlint"
  needs:
    - "testbuild_alpine_markdownlint"

security_alpine_git:
  <<: *security
  variables:
    TYPE: "Publish"
    NAME: "alpine-git"
  needs:
    - "testbuild_alpine_git"

security_alpine_releasecli:
  <<: *security
  variables:
    TYPE: "Publish"
    NAME: "alpine-releasecli"
  needs:
    - "testbuild_alpine_releasecli"

############################################
#### publish
############################################

publish_debian_11_ansible:
  <<: *publish
  variables:
    TYPE: "Ansible"
    NAME: "debian-11-ansible"
  needs:
    - "security_debian_11_ansible"

publish_debian_12_ansible:
  <<: *publish
  variables:
    TYPE: "Ansible"
    NAME: "debian-12-ansible"
  needs:
    - "security_debian_12_ansible"

publish_docker_dind_ansible:
  <<: *publish
  variables:
    TYPE: "Ansible"
    NAME: "docker-dind-ansible"
  needs:
    - "security_docker_dind_ansible"

publish_docker_dind_molecule:
  <<: *publish
  variables:
    TYPE: "Ansible"
    NAME: "docker-dind-molecule"
  needs:
    - "security_docker_dind_molecule"

publish_ubuntu_22_ansible:
  <<: *publish
  variables:
    TYPE: "Ansible"
    NAME: "ubuntu-22-ansible"
  needs:
    - "security_ubuntu_22_ansible"

publish_debian_11_certification:
  <<: *publish
  variables:
    TYPE: "Build"
    NAME: "debian-11-certification"
  needs:
    - "security_debian_11_certification"

publish_debian_npmbuild:
  <<: *publish
  variables:
    TYPE: "Build"
    NAME: "debian-npmbuild"
  needs:
    - "security_debian_npmbuild"

publish_docker_dockerfilebuild:
  <<: *publish
  variables:
    TYPE: "Build"
    NAME: "docker-dockerfilebuild"
  needs:
    - "security_docker_dockerfilebuild"

publish_alpine_ansiblelint:
  <<: *publish
  variables:
    TYPE: "Lint"
    NAME: "alpine-ansiblelint"
  needs:
    - "security_alpine_ansiblelint"

publish_alpine_dockerfilelint:
  <<: *publish
  variables:
    TYPE: "Lint"
    NAME: "alpine-dockerfilelint"
  needs:
    - "security_alpine_dockerfilelint"

publish_alpine_jinjalint:
  <<: *publish
  variables:
    TYPE: "Lint"
    NAME: "alpine-jinjalint"
  needs:
    - "security_alpine_jinjalint"

publish_alpine_secretlint:
  <<: *publish
  variables:
    TYPE: "Lint"
    NAME: "alpine-secretlint"
  needs:
    - "security_alpine_secretlint"

publish_alpine_sonarcli:
  <<: *publish
  variables:
    TYPE: "Lint"
    NAME: "alpine-sonarcli"
  needs:
    - "security_alpine_sonarcli"

publish_alpine_yamllint:
  <<: *publish
  variables:
    TYPE: "Lint"
    NAME: "alpine-yamllint"
  needs:
    - "security_alpine_yamllint"

publish_alpine_markdownlint:
  <<: *publish
  variables:
    TYPE: "Lint"
    NAME: "debian-markdownlint"
  needs:
    - "security_alpine_markdownlint"

publish_alpine_git:
  <<: *publish
  variables:
    TYPE: "Publish"
    NAME: "alpine-git"
  needs:
    - "security_alpine_git"

publish_alpine_releasecli:
  <<: *publish
  variables:
    TYPE: "Publish"
    NAME: "alpine-releasecli"
  needs:
    - "security_alpine_releasecli"
