############################################
#### lint
############################################

hadolint_debian_11_ansible:
  <<: *hadolint
  variables:
    TYPE: "Ansible"
    NAME: "debian-11-ansible"

hadolint_debian_12_ansible:
  <<: *hadolint
  variables:
    TYPE: "Ansible"
    NAME: "debian-12-ansible"

hadolint_docker_dind_ansible:
  <<: *hadolint
  variables:
    TYPE: "Ansible"
    NAME: "docker-dind-ansible"

hadolint_docker_dind_molecule:
  <<: *hadolint
  variables:
    TYPE: "Ansible"
    NAME: "docker-dind-molecule"

hadolint_ubuntu_22_ansible:
  <<: *hadolint
  variables:
    TYPE: "Ansible"
    NAME: "ubuntu-22-ansible"

hadolint_debian_11_certification:
  <<: *hadolint
  variables:
    TYPE: "Build"
    NAME: "debian-11-certification"

hadolint_debian_npmbuild:
  <<: *hadolint
  variables:
    TYPE: "Build"
    NAME: "debian-npmbuild"

hadolint_docker_dockerfilebuild:
  <<: *hadolint
  variables:
    TYPE: "Build"
    NAME: "docker-dockerfilebuild"

hadolint_alpine_ansiblelint:
  <<: *hadolint
  variables:
    TYPE: "Lint"
    NAME: "alpine-ansiblelint"

hadolint_alpine_dockerfilelint:
  <<: *hadolint
  variables:
    TYPE: "Lint"
    NAME: "alpine-dockerfilelint"

hadolint_alpine_jinjalint:
  <<: *hadolint
  variables:
    TYPE: "Lint"
    NAME: "alpine-jinjalint"

hadolint_alpine_secretlint:
  <<: *hadolint
  variables:
    TYPE: "Lint"
    NAME: "alpine-secretlint"

hadolint_alpine_alpine_sonarcli:
  <<: *hadolint
  variables:
    TYPE: "Lint"
    NAME: "alpine-sonarcli"

hadolint_alpine_yamllint:
  <<: *hadolint
  variables:
    TYPE: "Lint"
    NAME: "alpine-yamllint"

hadolint_alpine_markdownlint:
  <<: *hadolint
  variables:
    TYPE: "Lint"
    NAME: "debian-markdownlint"

hadolint_alpine_git:
  <<: *hadolint
  variables:
    TYPE: "Publish"
    NAME: "alpine-git"

hadolint_alpine_releasecli:
  <<: *hadolint
  variables:
    TYPE: "Publish"
    NAME: "alpine-releasecli"