# You can override the included template(s) by including variable overrides
# SAST customization: https://docs.gitlab.com/ee/user/application_security/sast/#customizing-the-sast-settings
# Secret Detection customization: https://docs.gitlab.com/ee/user/application_security/secret_detection/#customizing-settings
# Dependency Scanning customization: https://docs.gitlab.com/ee/user/application_security/dependency_scanning/#customizing-the-dependency-scanning-settings
# Container Scanning customization: https://docs.gitlab.com/ee/user/application_security/container_scanning/#customizing-the-container-scanning-settings
# Note that environment variables can be set in several places
# See https://docs.gitlab.com/ee/ci/variables/#cicd-variable-precedence

variables:
  ANSIBLE_FORCE_COLOR: "true"
  PY_COLORS: "1"
  #
  SONAR_HOST_URL: "$SONARQUBE_ADDRESS"
  SONAR_TOKEN: "$GITLAB_CI_SONARQUBE_USER_TOKEN"
  #
  DOCKER_IMAGE__ANALYSE_SONAR_SCANNER: "labocbz/analyse-sonar-scanner:0.15"
  DOCKER_IMAGE__ANALYSE_DOCKER_IMAGE: "labocbz/analyse-docker-image:latest"
  DOCKER_IMAGE__BUILD_DOCKERFILE: "labocbz/build-dockerfile:latest"
  DOCKER_IMAGE__LINT_DOCKERFILE: "labocbz/lint-dockerfile:latest"
  DOCKER_IMAGE__LINT_SECRETS: "labocbz/lint-secrets:latest"
  DOCKER_IMAGE__LINT_MARKDOWN: "labocbz/lint-markdown:latest"
  DOCKER_IMAGE__RUN_SSH: "labocbz/run-ssh:0.4"

image: $NEXUS_DOCKER_GROUP_REGISTRY/$DOCKER_IMAGE__RUN_SSH

stages:
  - gitlab-test
  - generate
  - build
  - scout-analyse
  - publish
  - lint
  - sonarqube-check

###############################################################################
#################### EXTENDABLES
###############################################################################

.build: &build
  stage: build
  image: $NEXUS_DOCKER_GROUP_REGISTRY/$DOCKER_IMAGE__BUILD_DOCKERFILE
  script:
    - "cd $(pwd)/${TYPE}/${NAME}/latest && bash build --test"
  allow_failure: false
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
    - if: '$CI_COMMIT_BRANCH == "develop"'

.scout-analyse: &scout-analyse
  stage: scout
  image: $NEXUS_DOCKER_GROUP_REGISTRY/$DOCKER_IMAGE__ANALYSE_DOCKER_IMAGE
  script:
    - "cd $(pwd)/${TYPE}/${NAME}/latest"
    - "bash build --scout"
    - "cd ../../../ && pwd"
    - "docker scout cves --exit-code --only-severity critical,high --format markdown --output ./cves-report.md local://local/${NAME}:latest-scout || true"
    - "docker scout recommendations local://local/${NAME}:latest-scout || true"
  allow_failure: true
  artifacts:
    expire_in: "1 month"
    paths:
      - "cves-report.md"
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
    - if: '$CI_COMMIT_BRANCH == "develop"'

.publish: &publish
  stage: publish
  image: $NEXUS_DOCKER_GROUP_REGISTRY/$DOCKER_IMAGE__BUILD_DOCKERFILE
  script:
    - "cd $(pwd)/${TYPE}/${NAME}/latest && bash build --cicd"
  allow_failure: false
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
#
#
#
